language: node_js
node_js:
- "stable"
notifications:
  email: false
env:
global:
  - export NODE_ENV=test
before_script:
  - npm install
  - npm i nyc --save-dev
script:
  - npm test
after_success:
  - npm run coverage
  - npm run coveralls








cache:
  directories:
    - node_modules

before_script:
  - npm i nyc --save-dev

script:
  - npm run test